### ISSUE TITLE
Deduper gives JS error, but only when debugging is disabled

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/deduper#27]
* I have a D9.4.5 site with minimal Drupal modules and a moderate number of Civi extensions.
* When I enable deduper, then visit either the deduper page or Mosaico (but not *all* Angular pages - SK, API4 Explorer, Data Explorer all work fine), I get an error.  After 3 rounds of HTML entity decoding, it looks like this:

```
Uncaught Error: [$injector:modulerr] 
http://errors.angularjs.org/1.8.2/$injector/modulerr?p0=crmApp&p1=[$injector:modulerr] 
http://errors.angularjs.org/1.8.2/$injector/modulerr?p0=afformStandalone&p1=[$injector:modulerr] 
http://errors.angularjs.org/1.8.2/$injector/modulerr?p0=dedupeSearchTasks&p1=[$injector:nomod] 
http://errors.angularjs.org/1.8.2/$injector/nomod?p0=dedupeSearchTasks
F/<@
https://connect.plasticpollutioncoalition.org/libraries/civicrm/core/bower_components/angular/angular.min.js?r=9mVc0en_US:7:168
Me/</</<@
https://connect.plasticpollutioncoalition.org/libraries/civicrm/core/bower_components/angular/angular.mi
```

I was getting different behavior on live and dev sites, which confused me until I saw in [AngularJS Quick Start docs](https://docs.civicrm.org/dev/en/latest/framework/angular/quickstart/), "By default, CiviCRM aggregates AngularJS files and caches them."  This only happens with debugging turned off.

If I delete `dedupeSearchTasks.ang.php` I get the same error on the `deduper` module.  If I also delete `deduper.ang.php` I get no error, but then of course the page doesn't load.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon does ^^ fix?

**Comment by seamuslee001** [comment]
@eileenmcnaughton I was working on this for Jon's client and no, I found that there was a conflict between this extension and Mathieu's data explorer but If I removed Lines 3-9 here https://lab.civicrm.org/extensions/dataexplorer/-/blob/master/ang/dataexplorer/DataExplorer.js#L3 then it worked with both extensions enabled. I am still very confused. I did run into one issue which I have put up as #28

**Comment by eileenmcnaughton** [comment]
Should we close this now?
