### ISSUE TITLE
[Add Clause]  broken on WP6.1.1 and Civicrm 5.57.0

### ISSUE THREAD

**Issue by speleo** [eileenmcnaughton/deduper#32]
selecting an entity from the [Add Clause] dialog has no effect.  
Using Chrome  109.0.5414.120
Have tried differnt templates but no joy.
![Capture](https://user-images.githubusercontent.com/2269143/216160412-c5f34a52-a23b-4fe2-af79-1299180125dc.JPG)

**Comment by eileenmcnaughton** [comment]
If you open the console in your browser is there a js error?

**Comment by speleo** [comment]
When I click on an item in the drop down dialog I get this msg in both Chrome and Edge

2angular.js:15697 
TypeError: Cannot read properties of null (reading '~/deduper/crmSearchSelector.html')
    at Object.getUrl (angular-modules.fb1db948d970d5809719cb3c67590cbb.js:233:43)
    at $delegate.get (angular-modules.fb1db948d970d5809719cb3c67590cbb.js:234:307)
    at g (angular.js:21542:43)
    at ha (angular.js:10966:7)
    at aa (angular.js:10509:24)
    at Xa (angular.js:9865:15)
    at Xa (angular.js:9877:15)
    at da (angular.js:9746:15)
    at angular.js:10215:22
    at d (angular.js:9985:16)
(anonymous) @ angular.js:15697

**Comment by eileenmcnaughton** [comment]
I've just tagged a new release (1.7) in order to have a clear code set with deduper

**Comment by speleo** [comment]
Perfect - 1.7 looks like it has fixed it for me.  Drop downs working as expected.  Many thanks.

**Comment by eileenmcnaughton** [comment]
Yay great - it was a while since a release was tagged so good to have gotten it tagged

Unrelated - I see you have repos related to cave data in the philippines - is that related at all to how you use Civi? Looks like an interesting project

**Comment by speleo** [comment]
Hi Eileen,

I've been using Civi for a long time now for my Caving Club.  When I first
started out I was looking for a "club management system" that would manage
online and offline members.  CiviMember had just come out so it must have
been around 2007/2008.  So I've been using Civi for some time.  Software is
not really my thing.  I do tech sales around solving the biggest problems
out there with High Performance Computing but mainly on the hardware side.

Cave survey data is stored in text files and we use software to define the
surveys and then get software to draw it for us.  That makes Git a really
useful tool to collaborate and share information.  Caving is one of the
true forms of exploration still out there.  You can see on Google Earth
what a mountain looks like, but what lies underneath is a mystery, there to
be unravelled.

As an aside, Matt Wire was a member of my Club and got interested enough to
be one of the more active folk in the Civi community.  It's a small world.

Henry

**Comment by eileenmcnaughton** [comment]
Thanks @speleo - that's an interesting back story and of course it did launch @mattwire into the world of Civi :-)
