### ISSUE TITLE
Issue on install

### ISSUE THREAD

**Issue by geekplm** [eileenmcnaughton/deduper#33]
Hello, 
While installing this extension, I've got the following error: 
```Cannot execute INSERT INTO civicrm_contact_name_pair_family (id, name_a, name_b, is_most_common_form, is_active) VALUES (65, 'Takahashi', '髙𣘺', 0, 1): DB Error: unknown error```
Any idea?
Thx,

**Comment by eileenmcnaughton** [comment]
That sounds like your database might not be using the ` utf8mb4` CHARSET which adds emoji / other character support

The configuration is on both a DB & per table basis & you will hit issues without being converted. To change just a table

```ALTER TABLE civicrm_contact_name_pair_family CHARACTER SET utf8mb4`

but you will probably hit issues elsewhere if your database is not utf8mb4

https://civicrm.stackexchange.com/questions/37937/what-does-it-mean-to-configure-your-mysql-server-for-utf8mb4-support-when-my-d
https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html


As an aside it's likely you don't need that table & could comment it out of the install since it's quite a specific feature

**Comment by christianwach** [comment]
@eileenmcnaughton This could be solved by changing this Extension's `CREATE TABLE` definitions from:

```
ENGINE=InnoDB;
```

To:

```
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

As indeed Core does 😄

Works for me.

**Comment by christianwach** [comment]
@eileenmcnaughton Having said that, I don't think Core should be calling `die()` when the SQL fails:

https://github.com/civicrm/civicrm-core/blob/fd4913060d8e944a99abe30c22ba670ed0e51a9a/CRM/Utils/File.php#L327

Perhaps that got missed when the conversion to `Exception`s took place?

I'll open an issue on Lab when I get a moment.

**Comment by eileenmcnaughton** [comment]
ug @christianwach -now I've seen that I can't unsee it.

Are you able to put up a patch for this extension?
