### ISSUE TITLE
Dependency `afform` not found, required by `deduper`

### ISSUE THREAD

**Issue by danfish** [eileenmcnaughton/deduper#5]
Eileen,

What's afform?

Thanks 

Daniel

**Comment by eileenmcnaughton** [comment]
It's https://civicrm.org/blog/josh/form-builder-gui-presented-by-coleman-watts - but I'm still figuring out how to get this to work as a downloadable version - I had it working for us but I am targetting 5.22 civi with Afform as the downloadable release. 

As of right now I'm adapting deduper to some changes made in afform  over the last few months
