### ISSUE TITLE
Error message when installing

### ISSUE THREAD

**Issue by MichPoe** [eileenmcnaughton/deduper#7]
Wordpress 5.22, pressing the install button leads to following message:

"Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Unknown extension: org.civicrm.afform"

**Comment by eileenmcnaughton** [comment]
Afform is a dependency  - https://lab.civicrm.org/extensions/afform - it might not be present?

**Comment by MichPoe** [comment]
Yes, thank you!
